name: ArcanePlotsPlugin
version: RC.3.0 for 1.7.10
author: Morios
description: Protects blocks from being removed / placed in an area.
#depend: CreditsPlugin

main: plots.ArcanePlotsPlugin

commands:
  credits:
    description: View saved credits or give them to someone.
    usage: "/credits [give <name> #] / blank (defaults to listing your balance)"

  plot buy:
    description: Purchase a plot. Can create by corners or radius.
    usage: "/plot buy [radius #] / [corners] / blank (defaults to 'radius')"
    
  plot sell:
    description: Sells a plot back.
    usage: "/plot sell"
    
  plot modify:
    description: Adds / removes a user from the owner list.
    usage: "/plot modify [+ <name>] / [- <name>]"
    
  plot list:
    description: Lists who is an owner of this plot. You don't need ownership to use this.
    usage: "/plot list"
    
  plot edit:
    description: Controls the state of a plot's protection.
    usage: "/plot edit [on] / [off] / blank (to toggle)"
    
  confirm:
    description: Confirm placing or removing a Plot.
    usage: "/plot confirm"
    
  cancel:
    description: Cancel placing or removing a Plot.
    usage: "/plot cancel"
    
  plot:
    description: Arcane Plots' main command. Defaults to 'plot list'
    usage: "/plot [command] [options]"

permissions:
  arcanePlotsPlugin.console:
    description: This allows use of the 'list all' and 'unset all' commands.
    default: false
    
  arcanePlotsPlugin.admin:
    description: This allows use of plot commands without being on their edit list.
    default: op

